version: '2'
services:
  database:
    image: josephkphan/oracledb:latest
    volumes:
      - ~/oracle_db2/oradata:/opt/oracle/oradata # persistent oracle database data.
    restart: always
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=mysecretpassword
